# site settings
title: ECHS 3DPC
subtitle: 
email: yhjc2692@gmail.com
description: Spreading the skill of engineering, the joy of 3D Printing
baseurl: # the subpath of your site, e.g. /blog
url: http://echs3dp.club # the base hostname & protocol for your site
author: Jason Cho
street_address: Room 2##
city: 9th Grade Building
state: 1st
zip_code: floor
country: East Coweta High School
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
